### ISSUE TITLE
How to ignore HTTPS certificate errors when using AtataContext.GlobalConfiguration.AutoSetUpConfiguredDriversAsync()

### ISSUE THREAD

**Issue by mamift** [atata-framework/atata-webdriversetup#13]
Hello,

So I've recently upgraded my Atata project from 1.x to 2.x (currently using Atata.WebDriverSetup 2.5.0) and everything builds properly, but I can't run my tests yet, as in my test setup logic, I am using `AtataContext.GlobalConfiguration.AutoSetUpConfiguredDriversAsync()` and it keeps throwing an exception at this point:
```
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__4.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__52.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__53.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<GetHttpConnectionAsync>d__45.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__71.MoveNext()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__35.MoveNext()
   at Atata.WebDriverSetup.HttpRequestExecutor.DownloadString(String url)
   at Atata.WebDriverSetup.ReliableHttpRequestExecutor.<>c__DisplayClass5_0.<DownloadString>b__0()
   at Atata.WebDriverSetup.ReliableHttpRequestExecutor.ExecuteWithRetries[TResult](Func`1 operation)
   at Atata.WebDriverSetup.ReliableHttpRequestExecutor.DownloadString(String url)
   at Atata.WebDriverSetup.ChromeDriverSetupStrategy.GetDriverVersionCorrespondingToBrowserVersion(String browserVersion)
   at Atata.WebDriverSetup.XmlFileDriverVersionCache.GetOrAdd(String browserVersion, DateTime minimumAcceptableTimestamp, Func`2 versionResolveFunction)
   at Atata.WebDriverSetup.CachedDriverVersionCorrespondingToBrowserVersionResolver.GetDriverVersionCorrespondingToBrowserVersion(String browserVersion)
   at Atata.WebDriverSetup.DriverVersionResolver.ResolveByBrowserVersion(String version)
   at Atata.WebDriverSetup.DriverVersionResolver.ResolveCorrespondingVersion()
   at Atata.WebDriverSetup.DriverVersionResolver.ResolveCorrespondingOrLatestVersion()
   at Atata.WebDriverSetup.DriverSetupConfigurationBuilder.ResolveDriverVersion(IDriverSetupStrategy setupStrategy, String version)
   at Atata.WebDriverSetup.DriverSetupConfigurationBuilder.ExecuteSetUp()
   at Atata.WebDriverSetup.DriverSetupConfigurationBuilder.SetUp()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Atata.WebDriverSetup.DriverSetupConfigurationBuilder.<SetUpAsync>d__13.MoveNext()
   at Atata.WebDriverSetup.DriverSetup.<AutoSetUpAsync>d__27.MoveNext()
   at Atata.WebDriverSetup.DriverSetup.<AutoSetUpAsync>d__29.MoveNext()
   at Atata.WebDriverSetup.DriverSetup.<AutoSetUpSafelyAsync>d__31.MoveNext()
   at Atata.WebDriverSetup.DriverSetup.AutoSetUpSafely(IEnumerable`1 browserNames)
   at Atata.MethodInfoExtensions.InvokeStaticAsLambda(MethodInfo method, Object[] args)
   at Atata.AtataContextBuilder.InvokeAutoSetUpSafelyMethodOfDriverSetup(IEnumerable`1 browserNames)
   at Atata.AtataContextBuilder.AutoSetUpDriverToUse()
   at OurClientMatters.UiTests.SetUpFixture.GlobalSetUp() in C:\Users\mmiftah\source\repos\OCM\OCM.UiTests\SetUpFixture.cs:line 23
```

I know what the cause of the issue is: my work network has MITM-HTTPS decryption, so all the HTTPS certificates resolve to a top-level CA that is self-signed, so it will always been invalid. Is there any way to configure the call to `AutoSetUpConfiguredDriversAsync()` to ignore HTTPS certificate errors?

I note that it calls `Atata.WebDriverSetup.DriverSetup.AutoSetUpSafely(IEnumerable``1 browserNames)`, which is why I posted the issue here.

**Comment by YevgeniyShunevych** [comment]
Can you try to add the following line to your global setup method before the AtataContext configuration:

```cs
ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
```

If it works for you, I will think about the cleaner solution to add to Atata.WebDriverSetup library.

**Comment by mamift** [comment]
Unfortunately no this didn't work:
![image](https://user-images.githubusercontent.com/2508444/235810705-358505f2-62ac-4a47-8e81-ba52dac0630c.png)

What's weird is that this worked in version 1.x perfectly fine. I was using Atata.WebDriverSetup 1.2.0 and also Atata 1.12.0 where it worked.

**Comment by YevgeniyShunevych** [comment]
I believe that it happens because of `CheckCertificateRevocationList` property of `HttpClientHandler`, which became enabled by default in Atata.WebDriverSetup v2.0.0. Let's try to disable it, which is now possible with the latest v2.6.0 release. So please update the Atata.WebDriverSetup package to the latest version. Then you can try one of the code blocks, again in global setup method before the `AtataContext` configuration.

```cs
DriverSetup.GlobalConfiguration
    .WithCheckCertificateRevocationList(false);
```

or

```cs
DriverSetup.GlobalConfiguration
    .WithCheckCertificateRevocationList(false)
    .WithHttpClientHandlerConfiguration(x => x.ServerCertificateCustomValidationCallback += (_, _, _, _) => true);
```

*And you can remove `ServicePointManager.ServerCertificateValidationCallback += ...` code.*

**Comment by mamift** [comment]
Thank you - I can confirm that:

`DriverSetup.GlobalConfiguration
    .WithHttpClientHandlerConfiguration(x => x.ServerCertificateCustomValidationCallback += (_, _, _, _) => true);`

resolves the issue for me. `DriverSetup.GlobalConfiguration.WithCheckCertificateRevocationList(false);` had no effect.

**Comment by YevgeniyShunevych** [comment]
You are welcome. Thanks for letting know which method solved the issue.
